
spring:
  # Redis
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password: ''
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flow?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
    username: root
    password: 123456
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: P@ssword
        allow:
      web-stat-filter:
        enabled: true

# acTable的配置信息 自动创建表，如果有更新则更新表
actable:
  table:
    auto: update
  model:
    pack: com.qlj.flow.entity
  database:
    type: mysql


mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    db-config:
      id-type: uuid

